action_type: straight-line-navigation
batch_size: 128
checkpoint_interval: 3000
checkpoint_path: checkpoint/checkpoint.pt
environment: 2
epsilon_end: 0.01
epsilon_start: 1.0
epsilon_steps: 200000
gamma: 0.99
log_file: output_logs/train.log
lr: 0.0005
ministep_size: 0.25
model: resnet
no_goal_timeout: 2000
num_boxes: 5
num_epochs: 50
num_of_batches_before_train: 5
replay_buffer_size: 10000
state_type: vision
target_update_freq: 20

# Rewards
collision_penalty:      10
action_penalty:         1
push_reward:            1
obj_to_goal_reward:     1000
exploration_reward:     0.1
partial_rewards_scale:  1