action_type: straight-line-navigation
batch_size: 128
checkpoint_interval: 3000
checkpoint_path: checkpoint/checkpoint-normal_rews.pt
environment: 2
epsilon_end: 0.01
epsilon_start: 1.0
epsilon_steps: 7000
gamma: 0.99
log_file: output_logs/train-normal_rews.log
lr: 0.0005
ministep_size: 0.25
model: resnet
no_push_timeout: 100
num_epochs: 100
num_of_batches_before_train: 10
replay_buffer_size: 10000
state_type: vision
target_update_freq: 1000

# Rewards
collision_penalty:      10
action_penalty:         0
push_reward:            1
obj_to_goal_reward:     1000
exploration_reward:     0.1
partial_rewards_scale:  1

# collision_penalty:      0.25
# action_penalty:         0
# push_reward:            0
# obj_to_goal_reward:     1
# exploration_reward:     0
# partial_rewards_scale:  1