action_freq: 25
action_type: straight-line-navigation
batch_size: 2
checkpoint_interval: 3000
checkpoint_path: checkpoint/checkpoint-test.pt
environment: 2
epsilon_end: 0.01
epsilon_start: 1.0
epsilon_steps: 6000
gamma: 0.99
log_file: output_logs/train-test.log
lr: 0.0005
ministep_size: 0.25
model: resnet
no_goal_timeout: 250
num_boxes: 5
num_epochs: 100
num_of_batches_before_train: 1000
num_policies: 2
options: True
replay_buffer_size: 10000
state_type: vision
target_update_freq: 1000

# Rewards
collision_penalty:      10
action_penalty:         0
push_reward:            1
no_movement_penalty:    1
obj_to_goal_reward:     100
exploration_reward:     0.1
partial_rewards_scale:  2