action_freq: 1
action_type: primitive
batch_size: 128
checkpoint_interval: 3000
checkpoint_path: checkpoint/checkpoint-push_reward.pt
model_path: model_weights/model-push_reward.pt
environment: 3
epsilon_end: 0.01
epsilon_start: 1.0
epsilon_steps: 10000
gamma: 0.99
log_file: output_logs/train-push_reward.log
lr: 0.0005
ministep_size: 0.25
model: resnet
no_goal_timeout: 1000
num_boxes: 5
num_epochs: 500
num_of_batches_before_train: 10
num_policies: 1
options: False
replay_buffer_size: 10000
state_type: vision
target_update_freq: 1000

state_info: multiinfo

# Rewards
collision_penalty:      5
action_penalty:         0
no_movement_penalty:    0
push_reward:            0 #5
obj_to_goal_reward:     100
exploration_reward:     0
partial_rewards_scale:  1
corner_penalty:         0 #10

# Only need if environment is 3
box_uncertainty: 0.1
grid_size: 10